/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.agmip.ui.dssat1;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.Arrays;
import java.util.List;
import javax.swing.JTextField;
import org.agmip.ui.utils.FrameTracker;
import org.agmip.ui.utils.PathGenerator;
import org.agmip.ui.utils.WeatherFileSystem;

/**
 *
 * @author rohit
 */
public class ResultFrame extends javax.swing.JFrame {

    /**
     * Creates new form ResultFrame
     */
    public ResultFrame() {
        initComponents();
        
        initilalizePathFields();
        setLocation(400, 50);
        setResizable(false);
        
    }

    private void initilalizePathFields() {
        jSoilFilePathField.setText(PathGenerator.getSoilFilePath());
        System.out.println ("Soil File Path + " + PathGenerator.getSoilFilePath());
        
        JTextField [] jTextFields= new JTextField []{jPTXFileLocation, jBatchFileLocation};
        
        jSoilFilePathField.setEditable(false);
        jWeatherFilePathField.setText(PathGenerator.getWeatherFilePath());
        jWeatherFilePathField.setEditable(false);
        
        for (File f : PathGenerator.getTranslatorOutputPath()) {
            
            if (f.getAbsolutePath().contains("DSSBatch.v45")) {
                jBatchFileLocation.setText(f.getAbsolutePath());
                jBatchFileLocation.setEditable(false);
            } else if (f.getAbsolutePath().toUpperCase().charAt(f.getAbsolutePath().length()-1)=='X'){
                jPTXFileLocation.setText(f.getAbsolutePath());
                jPTXFileLocation.setEditable(false);
            }
            
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jSoilFilePathField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        viewSoilFileButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jWeatherFilePathField = new javax.swing.JTextField();
        viewWeatherFileButton = new javax.swing.JButton();
        runXFileButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jPTXFileLocation = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        viewXFileButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jBatchFileLocation = new javax.swing.JTextField();
        viewBatchFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Soil File Location");

        viewSoilFileButton.setText("View Soil File");
        viewSoilFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSoilFileButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Weather File Location");

        jWeatherFilePathField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWeatherFilePathFieldActionPerformed(evt);
            }
        });

        viewWeatherFileButton.setText("View Weather File");
        viewWeatherFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewWeatherFileButtonActionPerformed(evt);
            }
        });

        runXFileButton.setText("Run X File");
        runXFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runXFileButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("X File Location");

        viewXFileButton.setText("View X File");
        viewXFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewXFileButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Batch File Location");

        viewBatchFile.setText("View Batch File");
        viewBatchFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBatchFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(runXFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(backButton))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(528, 528, 528)
                                .addComponent(viewXFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPTXFileLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jWeatherFilePathField, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSoilFilePathField, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(viewWeatherFileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(viewSoilFileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(viewBatchFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBatchFileLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSoilFilePathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewSoilFileButton))
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jWeatherFilePathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewWeatherFileButton))
                .addGap(41, 41, 41)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBatchFileLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewBatchFile))
                .addGap(43, 43, 43)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPTXFileLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewXFileButton))
                .addGap(58, 58, 58)
                .addComponent(runXFileButton)
                .addGap(18, 18, 18)
                .addComponent(backButton)
                .addContainerGap(340, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jWeatherFilePathFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWeatherFilePathFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jWeatherFilePathFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        FrameTracker.second.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void viewSoilFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSoilFileButtonActionPerformed
        // TODO add your handling code here:
        OpenTxtFileEditor(PathGenerator.getSoilFilePath());
    }//GEN-LAST:event_viewSoilFileButtonActionPerformed

    private void viewWeatherFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewWeatherFileButtonActionPerformed
        // TODO add your handling code here:
        OpenTxtFileEditor(PathGenerator.getWeatherFilePath());
    }//GEN-LAST:event_viewWeatherFileButtonActionPerformed

    private void runXFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runXFileButtonActionPerformed
        // TODO add your handling code here:
        
        // TODO add your handling code here:
        File batchFile = new File ("RunDSSAT2D.bat");
        PrintWriter fileWriter = null;
        
        
        try {
            if (!batchFile.exists()) {
                batchFile.createNewFile();
            }

            String dssatFolderPath = PathGenerator.getDssatInstallationFolder();
 
            fileWriter = new PrintWriter(batchFile);
            // Build crop absolute path 
            String cropFolderPath = PathGenerator.getCropDirectory();
            String batchFilePath = cropFolderPath   + "\\" + "DSS40.v45";
            String exeFilePath = dssatFolderPath + "\\" + "DSSAT_2D.exe";
            String runCommand = exeFilePath + " b " + batchFilePath;
            
            // C:\DSSAT45\dscsm045.exe b C:\DSSAT45\potato\DSS40.v45            
            // Validate if the exe file is available in the exeFilePath or not. If it is not 
            // available then we need to copy this from the current folder into the DSSAT folder.

            String currentDir = System.getProperty("user.dir");

            if (!(new File(exeFilePath).exists())) {

                Files.copy(Paths.get(currentDir+"\\src\\main\\resources\\executable\\DSSAT_2D.exe"), Paths.get(exeFilePath), StandardCopyOption.COPY_ATTRIBUTES);
            }
            
            String drive = dssatFolderPath.substring(0, 2);
            fileWriter.println(drive);
            fileWriter.println("cd " + dssatFolderPath);
            fileWriter.println(runCommand);
            fileWriter.println("@echo off");            
            fileWriter.println("pause");            
            fileWriter.println("exit");
        } catch (IOException e) {
            
        } finally {
            fileWriter.close();
        }
        
        /*try {
            Runtime.getRuntime().exec("cmd /c RunDSSAT2D.bat");
        } catch (IOException e) {
            e.printStackTrace();
        }*/
        
        
        // Batch File execution
        List cmdAndArgs = Arrays.asList("cmd", "/c", "RunDSSAT2D.bat");
        File dir = new File(".");

        ProcessBuilder pb = new ProcessBuilder(cmdAndArgs);
        pb.directory(dir);
        
        try {
            Process p = pb.start();
            System.out.println ("Executed the file");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_runXFileButtonActionPerformed

    private void viewXFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewXFileButtonActionPerformed
        // TODO add your handling code here:
        OpenTxtFileEditor(jPTXFileLocation.getText());
    }//GEN-LAST:event_viewXFileButtonActionPerformed

    private void viewBatchFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBatchFileActionPerformed
        // TODO add your handling code here:
        OpenTxtFileEditor(jBatchFileLocation.getText());
    }//GEN-LAST:event_viewBatchFileActionPerformed

        private void OpenTxtFileEditor(String filepath) {

        try {
            if (System.getProperty("os.name").toLowerCase().contains("windows")) {
                String cmds[] = new String[]{"notepad", filepath};
                Runtime.getRuntime().exec(cmds);
            } else {
                File file = new File(filepath);
                Desktop.getDesktop().browse(file.toURI());
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField jBatchFileLocation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jPTXFileLocation;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jSoilFilePathField;
    private javax.swing.JTextField jWeatherFilePathField;
    private javax.swing.JButton runXFileButton;
    private javax.swing.JButton viewBatchFile;
    private javax.swing.JButton viewSoilFileButton;
    private javax.swing.JButton viewWeatherFileButton;
    private javax.swing.JButton viewXFileButton;
    // End of variables declaration//GEN-END:variables
}
